from typing import Optional, List, Dict, Any
from models.history import HistoryRecargaSchema, HistoryRecargaSchemaDB, HistoryManutencaoSchema, HistoryManutencaoSchemaDB

#Filtros sao coisas como data e id

async def create_history_recharge(history: HistoryRecargaSchema) -> HistoryRecargaSchema:
    ...

async def create_history_maintenance(history: HistoryManutencaoSchema) -> HistoryManutencaoSchema:
    ...

async def get_history_recharge(filters: Optional[Dict[str, Any]] = None) -> List[HistoryRecargaSchemaDB]:
    if filters:
        ...
    ...

async def get_history_maintenance(filters: Optional[Dict[str, Any]] = None) -> List[HistoryManutencaoSchemaDB]:
    if filters:
        ...
    ...

async def update_history_recharge(id: int, history: HistoryRecargaSchema):
    ...

async def update_history_maintenance(id: int, history: HistoryManutencaoSchema):
    ...

async def delete_history_recharge(id: int):
    ...

async def delete_history_maintenance(id: int):
    ...