"""add timestamp in  ApiKeyLog

Revision ID: 800f9cc664c2
Revises: d2f46fbd136c
Create Date: 2025-06-27 10:43:28.010332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '800f9cc664c2'
down_revision: Union[str, Sequence[str], None] = 'd2f46fbd136c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key_log', sa.Column('timestamp', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_key_log', 'timestamp')
    # ### end Alembic commands ###
