"""id init=False in  ApiKeyLog

Revision ID: d2f46fbd136c
Revises: 9c1a4b372c0f
Create Date: 2025-06-27 10:21:10.065785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f46fbd136c'
down_revision: Union[str, Sequence[str], None] = '9c1a4b372c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
