"""updated_at bug fix for users

Revision ID: 5113f44ba52d
Revises: 209fdf24954a
Create Date: 2025-07-04 15:53:48.705702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5113f44ba52d'
down_revision: Union[str, Sequence[str], None] = '209fdf24954a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key_permission', sa.Column('api_key_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('api_key_permission_user_id_fkey'), 'api_key_permission', type_='foreignkey')
    op.create_foreign_key(None, 'api_key_permission', 'user_api_key', ['api_key_id'], ['id'])
    op.drop_column('api_key_permission', 'user_id')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'member', name='usersrole'),
               type_=sa.Enum('admin', 'member', name='usersroleschema'),
               existing_nullable=False,
               postgresql_using='role::text::usersroleschema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'member', name='usersroleschema'),
               type_=postgresql.ENUM('admin', 'member', name='usersrole'),
               existing_nullable=False,
               postgresql_using='role::text::usersrole')
    op.add_column('api_key_permission', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('api_key_permission_api_key_id_fkey', 'api_key_permission', type_='foreignkey')
    op.create_foreign_key(op.f('api_key_permission_user_id_fkey'), 'api_key_permission', 'users', ['user_id'], ['id'])
    op.drop_column('api_key_permission', 'api_key_id')
    # ### end Alembic commands ###
