"""create permission id

Revision ID: ac98327cfe0c
Revises: 4aa4e0fa723f
Create Date: 2025-06-20 13:57:27.155596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac98327cfe0c'
down_revision: Union[str, Sequence[str], None] = '4aa4e0fa723f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('refill_history_supply_id_fkey'), 'refill_history', type_='foreignkey')
    op.add_column('users', sa.Column('permission_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'permissions', ['permission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'permission_id')
    op.create_foreign_key(op.f('refill_history_supply_id_fkey'), 'refill_history', 'supply', ['supply_id'], ['id'])
    # ### end Alembic commands ###
