"""bug fix: improved printer table relationship

Revision ID: b16f988b37fc
Revises: ee459cf7aa4a
Create Date: 2025-07-08 18:44:53.706090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16f988b37fc'
down_revision: Union[str, Sequence[str], None] = 'ee459cf7aa4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
