"""translate primeiro_acesso for first_access

Revision ID: bae5d0deaa05
Revises: 5113f44ba52d
Create Date: 2025-07-04 16:01:53.497616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae5d0deaa05'
down_revision: Union[str, Sequence[str], None] = '5113f44ba52d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_configuration', sa.Column('first_access', sa.Boolean(), nullable=False))
    op.drop_column('user_configuration', 'primeiro_acesso')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_configuration', sa.Column('primeiro_acesso', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user_configuration', 'first_access')
    # ### end Alembic commands ###
