"""add guest user

Revision ID: 6de5ac8a3616
Revises: 0c117ce3e118
Create Date: 2025-07-23 18:55:53.657023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de5ac8a3616'
down_revision: Union[str, Sequence[str], None] = '0c117ce3e118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Adiciona o novo valor 'guest' no enum `usersroleschema`.
    # O comando `ALTER TYPE ... ADD VALUE IF NOT EXISTS` garante idempotência caso o valor já exista.
    op.execute("ALTER TYPE usersroleschema ADD VALUE IF NOT EXISTS 'guest';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remover valores individuais de um ENUM no PostgreSQL não é suportado diretamente.
    # Para lidar com isso, recriamos o tipo sem o valor 'guest' e migramos a coluna.

    # 1. Renomeia o tipo existente.
    op.execute("ALTER TYPE usersroleschema RENAME TO usersroleschema_old;")

    # 2. Cria o novo tipo sem o valor 'guest'.
    from sqlalchemy.dialects import postgresql
    users_role_enum = postgresql.ENUM('admin', 'member', name='usersroleschema')
    users_role_enum.create(op.get_bind(), checkfirst=True)

    # 3. Altera a coluna para usar o novo tipo.
    op.execute("""
        ALTER TABLE users
        ALTER COLUMN role TYPE usersroleschema USING role::text::usersroleschema;
    """)

    # 4. Remove o tipo antigo.
    op.execute("DROP TYPE usersroleschema_old;")
    # ### end Alembic commands ###
