"""update table user configurations

Revision ID: f3606073f95b
Revises: bae5d0deaa05
Create Date: 2025-07-07 13:07:59.656916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3606073f95b'
down_revision: Union[str, Sequence[str], None] = 'bae5d0deaa05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_configuration', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_configuration', 'created_at')
    # ### end Alembic commands ###
